### ISSUE TITLE
Tillbakaknapp

### ISSUE THREAD

**Issue by Aliide** [lstenstadvold/Pfi3_Group1_FinalProject_Version2#1]
Appen kraschar när man trycker tillbaka när man är inne i scanning läget  @antonnyman

**Comment by antonnyman** [comment]
Kan ni posta vad ni får för felmeddelande i logcaten?

**Comment by lstenstadvold** [comment]
05-21 14:45:21.672  12624-12624/idk14.pfi3_finalproject_group1 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:0, request=49374, result=0, data=null} to activity {idk14.pfi3_finalproject_group1/idk14.pfi3_finalproject_group1.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3435)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3478)
            at android.app.ActivityThread.access$1200(ActivityThread.java:157)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5319)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at idk14.pfi3_finalproject_group1.StartFragment.onActivityResult(StartFragment.java:73)
            at android.app.Activity.dispatchActivityResult(Activity.java:5519)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3431)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3478)
            at android.app.ActivityThread.access$1200(ActivityThread.java:157)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5319)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by antonnyman** [comment]
This was solved by doing some more null checks.
